services:
  - type: web
    name: nanobot-service
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "18790"
      - key: NODE_OPTIONS
        value: "--max-old-space-size=300"
      - key: NODE_ENV
        value: "production"
